In [39]:
#https://peterroelants.github.io/posts/multivariate-normal-primer/

In [9]:
import numpy as np

In [10]:
x=[180,170,170,175,181,175,177,185,179,160]
y=[95,70,60,79,60,63,83,80,75,50]
x,y,len(x),len(y)

([180, 170, 170, 175, 181, 175, 177, 185, 179, 160],
 [95, 70, 60, 79, 60, 63, 83, 80, 75, 50],
 10,
 10)

In [11]:
X= np.stack((x,y), axis=0)
X

array([[180, 170, 170, 175, 181, 175, 177, 185, 179, 160],
       [ 95,  70,  60,  79,  60,  63,  83,  80,  75,  50]])

In [12]:
sigma_1=np.cov(X)
sigma_1

array([[ 50.62222222,  62.        ],
       [ 62.        , 180.72222222]])

In [15]:
X_test= np.stack((x,x), axis=0)
X_test

array([[180, 170, 170, 175, 181, 175, 177, 185, 179, 160],
       [180, 170, 170, 175, 181, 175, 177, 185, 179, 160]])

In [16]:
sigma_2=np.cov(X_test)
sigma_2

array([[50.62222222, 50.62222222],
       [50.62222222, 50.62222222]])

In [17]:
def generate_data():                                #Yukarıdaki işlemlerin toparlayıp fonksiyon olarak yazılmış hali
    x=[180,170,170,175,181,175,177,185,179,160]
    y=[95,70,60,79,60,63,83,80,75,50]
    X= np.stack((x,y), axis=0)
    return X
def get_cov_matris(X):
    sigma_1=np.cov(X)
    return sigma_1

In [19]:
data_1=generate_data()
get_cov_matris(data_1)

array([[ 50.62222222,  62.        ],
       [ 62.        , 180.72222222]])

In [20]:
def multivariate_normal(x, d, mean, covariance):
    """pdf of the multivariate normal distribution."""
    x_m = x - mean
    return (1. / (np.sqrt((2 * np.pi)**d * np.linalg.det(covariance))) * 
            np.exp(-(np.linalg.solve(covariance, x_m).T.dot(x_m)) / 2))

In [24]:
x=generate_data()
np.mean(x[0,:]),np.mean(x[1,:])

(175.2, 71.5)

In [33]:
x_1=[165,75]
d_1=2

data=generate_data()
mean_1=np.array([np.mean(x[0,:]),np.mean(x[1,:])])
covariance_1=get_cov_matris(data)

In [34]:
multivariate_normal(x_1,d_1,mean_1,covariance_1)

0.00023078264286091306

In [38]:
for i in range(20):
    v=164+i
    x_1=[v,72]
    s=multivariate_normal(x_1,d_1,mean_1,covariance_1)
    print(v," ",s)

164   0.00024129134356410783
165   0.0003494602240504495
166   0.0004891676040544105
167   0.0006617920579089789
168   0.0008653451053442342
169   0.0010936064403862017
170   0.0013357854355784107
171   0.0015769440170517823
172   0.001799284234571747
173   0.001984208019848437
174   0.002114845053089612
175   0.0021785816127892627
176   0.0021690673696961073
177   0.002087258197686197
178   0.0019412579031221158
179   0.0017449951542558295
180   0.0015160346965710169
181   0.0012729987684041739
182   0.0010331199622780874
183   0.0008103589816512312
